version: '3.7'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - 6381:6379
    volumes:
      - redis_data:/data
    networks:
      - my-app

  mongodb:
    image: mongo:7.0
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - my-app

  pasrsing-service:
    build:
      context: ./afisha-nest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    networks:
      - my-app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  redis_data:
  mongo_data:

networks:
  my-app: