version: '3.7'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - 6381:6379
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7.0
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: